version: '3.8'

services:
  redteam:
    image: redteam
    container_name: redteam
    hostname: redteam
    build:
      context: ./redteam
      args:
        SSHPASSWORD: ${SSHPASSWORD}
    ports:
      - "${RTSSHHOSTPORT}:22"
    restart: unless-stopped
    stdin_open: true  # Mantiene stdin abierto para la interacción
    tty: true         # Asigna una pseudo-TTY
    env_file:
      - .env
